export const dataPictures = [
  {
    id: 1,
    title: "Image 1",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL +"/Image/image1.jpg",
  },
  {
    id: 2,
    title: "Image 2",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image2.jpg",
  },
  {
    id: 3,
    title: "Image 3",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image3.jpg",
  },
  {
    id: 4,
    title: "Image 4",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image4.jpg",
  },
  {
    id: 5,
    title: "Image 5",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL +"/Image/image5.jpg",
  },
  {
    id: 6,
    title: "Image 6",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image6.jpg",
  },
  {
    id: 7,
    title: "Image 7",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image7.jpg",
  },
  {
    id: 8,
    title: "Image 8",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image8.jpg",
  },
  {
    id: 9,
    title: "Image 9",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image9.jpg",
  },
  {
    id: 10,
    title: "Image 10",
    upvotes: 0,
    downvotes: 0,
    hasStar: false,
    img: process.env.PUBLIC_URL + "/Image/image10.jpg",
  },
];
